/*
 * TropiCare — Clinical PDF Report Generator
 */
import { jsPDF } from "jspdf";

const TEAL   = [12, 138, 126];
const TEAL_D = [10, 107, 98];
const INK    = [11, 23, 38];
const MUTED  = [91, 107, 124];
const BORDER = [225, 229, 232];
const PANEL  = [248, 250, 250];

const RISK_RGB = {
  High:   [226, 61, 61],
  Medium: [232, 147, 15],
  Low:    [31, 157, 85],
  None:   [31, 157, 85],
};

const LINE_COLORS = [
  [12, 138, 126],
  [47, 111, 237],
  [232, 147, 15],
  [124, 92, 240],
  [226, 61, 61],
];

const PAGE_W     = 210;
const PAGE_H     = 297;
const MARGIN     = 16;
const CONTENT_W  = PAGE_W - MARGIN * 2;
const FOOTER_LIMIT = PAGE_H - 24;

// ─────────────────────────────────────────────
// READ STORED SESSION
// Reads the logged-in user straight from localStorage so patient info is
// always available regardless of which screen triggers the PDF download.
// ─────────────────────────────────────────────
function getStoredUser() {
  try {
    const raw = localStorage.getItem("tc_user");
    if (!raw) return {};
    const parsed = JSON.parse(raw);
    return parsed && typeof parsed === "object" ? parsed : {};
  } catch {
    return {};
  }
}

// ─────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────
function fmtDate(d) {
  const date = d ? new Date(d) : new Date();
  if (isNaN(date.getTime())) return fmtDate();
  return (
    date.toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" }) +
    " at " +
    date.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" })
  );
}

function makeReportId() {
  const now   = new Date();
  const stamp = now.toISOString().replace(/[-:T.]/g, "").slice(0, 14);
  return `TC-${stamp}`;
}

// Returns the first non-empty, non-null, non-"undefined" candidate value,
// or "Not provided" when none is available.
function field(...candidates) {
  for (const c of candidates) {
    if (c === undefined || c === null) continue;
    const str = String(c).trim();
    if (
      str.length > 0 &&
      str.toLowerCase() !== "undefined" &&
      str.toLowerCase() !== "null"
    ) {
      return str;
    }
  }
  return "Not provided";
}

function ensureSpace(doc, cursorY, needed) {
  if (cursorY + needed > FOOTER_LIMIT) {
    doc.addPage();
    return 24;
  }
  return cursorY;
}

function drawPageFooter(doc) {
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setDrawColor(...BORDER);
    doc.setLineWidth(0.2);
    doc.line(MARGIN, PAGE_H - 17, PAGE_W - MARGIN, PAGE_H - 17);
    doc.setFontSize(7.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...MUTED);
    doc.text(
      "TropiCare — AI-Guided Tropical Disease Symptom Checker",
      MARGIN,
      PAGE_H - 12
    );
    doc.text(
      `Page ${i} of ${totalPages}`,
      PAGE_W - MARGIN,
      PAGE_H - 12,
      { align: "right" }
    );
    doc.text(
      "This report is generated by an automated screening tool and does not constitute a clinical diagnosis.",
      MARGIN,
      PAGE_H - 7.5
    );
  }
}

function sectionLabel(doc, text, y) {
  doc.setFontSize(9.5);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...TEAL_D);
  doc.text(text.toUpperCase(), MARGIN, y);
  doc.setDrawColor(...TEAL);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, y + 2, PAGE_W - MARGIN, y + 2);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...INK);
  return y + 9;
}

// ─────────────────────────────────────────────
// HEADER
// ─────────────────────────────────────────────
function drawHeader(doc, reportId, dateStr) {
  doc.setFillColor(...TEAL);
  doc.rect(0, 0, PAGE_W, 30, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(19);
  doc.setFont("helvetica", "bold");
  doc.text("TropiCare", MARGIN, 14);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("Clinical Symptom Assessment Report", MARGIN, 21.5);

  doc.setFontSize(8);
  doc.text(`Report ID: ${reportId}`, PAGE_W - MARGIN, 12.5, { align: "right" });
  doc.text(`Generated: ${dateStr}`, PAGE_W - MARGIN, 18.5, { align: "right" });

  doc.setTextColor(...INK);
  return 41;
}

// ─────────────────────────────────────────────
// PATIENT INFO
// Merges the caller-supplied patient object with the stored session so
// email / age / gender are always available, regardless of which screen
// triggered the download.
// ─────────────────────────────────────────────
function drawPatientInfo(doc, patient, y) {
  const stored = getStoredUser();

  const name = field(
    patient?.name,
    patient?.full_name,
    patient?.patient_name,
    stored?.name
  );
  const email = field(
    patient?.email,
    patient?.patient_email,
    stored?.email
  );
  const ageRaw = field(
    patient?.age,
    patient?.patient_age,
    stored?.age
  );
  const age    = ageRaw !== "Not provided" ? `${ageRaw} years` : "Not provided";
  const gender = field(
    patient?.gender,
    patient?.patient_gender,
    stored?.gender
  );

  y = sectionLabel(doc, "Patient Information", y);

  const rows = [
    ["Name",          name  ],
    ["Email Address", email ],
    ["Age",           age   ],
    ["Gender",        gender],
  ];

  const colW = CONTENT_W / 2;
  const rowH = 14;

  doc.setFillColor(...PANEL);
  doc.setDrawColor(...BORDER);
  doc.roundedRect(MARGIN, y, CONTENT_W, rowH * 2, 2, 2, "FD");

  rows.forEach((row, i) => {
    const col    = i % 2;
    const rowIdx = Math.floor(i / 2);
    const x      = MARGIN + 6 + col * colW;
    const ry     = y + 7 + rowIdx * rowH;

    doc.setFontSize(7.2);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...MUTED);
    doc.text(row[0].toUpperCase(), x, ry);

    doc.setFontSize(10.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...INK);
    const valueLines = doc.splitTextToSize(row[1], colW - 12);
    doc.text(valueLines[0], x, ry + 5.5);
  });

  return y + rowH * 2 + 8;
}

// ─────────────────────────────────────────────
// CLINICAL SUMMARY
// ─────────────────────────────────────────────
function drawClinicalSummary(doc, diagnosis, y) {
  y = sectionLabel(doc, "Clinical Summary", y);

  const risk      = diagnosis.risk || "None";
  const rgb       = RISK_RGB[risk] || RISK_RGB.Medium;
  const confPct   = Math.round((diagnosis.confidence || 0) * 100);
  const hasExpl   = !!diagnosis.explanation;
  const explLines = hasExpl
    ? doc.splitTextToSize(diagnosis.explanation, CONTENT_W - 12)
    : [];
  const boxH = hasExpl ? 32 + explLines.length * 4.2 : 30;

  doc.setFillColor(...PANEL);
  doc.setDrawColor(...BORDER);
  doc.roundedRect(MARGIN, y, CONTENT_W, boxH, 2, 2, "FD");

  doc.setFontSize(7.5);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...MUTED);
  doc.text("PREDICTED CONDITION", MARGIN + 6, y + 8);

  doc.setFontSize(15);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...INK);
  const diseaseText  = diagnosis.disease || "No condition identified";
  const diseaseLines = doc.splitTextToSize(diseaseText, CONTENT_W - 48);
  doc.text(diseaseLines[0], MARGIN + 6, y + 17);

  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...MUTED);
  doc.text(`Model confidence: ${confPct}%`, MARGIN + 6, y + 24);

  const badgeW = 32;
  const badgeX = PAGE_W - MARGIN - badgeW - 6;
  doc.setFillColor(...rgb);
  doc.roundedRect(badgeX, y + 6, badgeW, 9.5, 4.75, 4.75, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text(`${risk} Risk`, badgeX + badgeW / 2, y + 12.3, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setTextColor(...INK);

  if (hasExpl) {
    doc.setFontSize(8.5);
    doc.setTextColor(...MUTED);
    doc.text(explLines, MARGIN + 6, y + 30);
  }

  return y + boxH + 8;
}

// ─────────────────────────────────────────────
// DIFFERENTIAL DIAGNOSIS
// ─────────────────────────────────────────────
function drawDifferential(doc, diagnosis, y) {
  const scores = diagnosis.all_scores || {};
  const others = Object.entries(scores)
    .filter(([d]) => d !== diagnosis.disease)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5);
  if (others.length === 0) return y;

  y = sectionLabel(doc, "Differential Diagnosis — Other Possibilities", y);

  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...MUTED);
  doc.text("CONDITION", MARGIN, y);
  doc.text("PROBABILITY", PAGE_W - MARGIN, y, { align: "right" });
  doc.setFont("helvetica", "normal");
  y += 3;
  doc.setDrawColor(...BORDER);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 6;

  const barW = 32;
  const barX = PAGE_W - MARGIN - barW - 14;

  others.forEach(([d, v]) => {
    const pct = Math.round(v * 100);
    doc.setFontSize(9.5);
    doc.setTextColor(...INK);
    const nameLines = doc.splitTextToSize(d, barX - MARGIN - 6);
    doc.text(nameLines[0], MARGIN, y + 3);

    doc.setFillColor(235, 238, 240);
    doc.roundedRect(barX, y, barW, 4, 1, 1, "F");
    doc.setFillColor(...MUTED);
    doc.roundedRect(barX, y, Math.max(barW * (pct / 100), 1.2), 4, 1, 1, "F");

    doc.setFontSize(8.5);
    doc.text(`${pct}%`, PAGE_W - MARGIN, y + 3.3, { align: "right" });
    y += 9;
  });

  return y + 2;
}

// ─────────────────────────────────────────────
// REPORTED SYMPTOMS
// ─────────────────────────────────────────────
function drawSymptoms(doc, symptoms, y) {
  if (!symptoms || symptoms.length === 0) return y;

  y = sectionLabel(doc, `Reported Symptoms (${symptoms.length})`, y);

  const labels = symptoms.map((s) => s.replace(/_/g, " "));
  doc.setFontSize(8.5);

  let x     = MARGIN;
  let lineY = y + 1;
  const chipH   = 6.5;
  const lineGap = 8.5;

  labels.forEach((label) => {
    const w = doc.getTextWidth(label) + 7;
    if (x + w > PAGE_W - MARGIN) {
      x = MARGIN;
      lineY += lineGap;
    }
    doc.setFillColor(238, 252, 250);
    doc.setDrawColor(189, 240, 234);
    doc.roundedRect(x, lineY - 4.6, w, chipH, 2, 2, "FD");
    doc.setTextColor(...TEAL_D);
    doc.text(label, x + 3.5, lineY);
    doc.setTextColor(...INK);
    x += w + 3;
  });

  return lineY + 9;
}

// ─────────────────────────────────────────────
// RECOMMENDATIONS
// ─────────────────────────────────────────────
function drawRecommendations(doc, rec, y) {
  if (!rec) return y;

  const items = [
    ["Home Care",            rec.home_care],
    ["Recommended Test",     rec.test     ],
    ["Doctor / Clinic Visit",rec.doctor   ],
    ["Safety Note",          rec.safety   ],
  ].filter((i) => i[1] && String(i[1]).trim().length > 0);

  if (items.length === 0) return y;

  y = sectionLabel(doc, "Clinical Recommendations", y);

  items.forEach(([label, text]) => {
    const lines = doc.splitTextToSize(String(text), CONTENT_W - 10);
    const boxH  = 9.5 + lines.length * 4.4;

    y = ensureSpace(doc, y, boxH + 4);

    doc.setFillColor(250, 250, 251);
    doc.setDrawColor(...BORDER);
    doc.roundedRect(MARGIN, y, CONTENT_W, boxH, 1.5, 1.5, "FD");

    doc.setFontSize(7.5);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...TEAL_D);
    doc.text(label.toUpperCase(), MARGIN + 5, y + 6);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...INK);
    doc.text(lines, MARGIN + 5, y + 11.5);

    y += boxH + 4;
  });

  return y + 2;
}

// ─────────────────────────────────────────────
// CONFIDENCE EVOLUTION CHART
// Only plots steps where the patient answered Yes — these are the only
// points that actually moved the model's reasoning. Each x-axis label
// sits directly beneath its own node via equal-slot positioning.
// ─────────────────────────────────────────────
function drawConfidenceChart(doc, trajectory, y) {
  if (!trajectory || trajectory.length === 0) return y;

  // Keep only confirmed (Yes) steps
  const confirmedSteps = trajectory.filter((step) => step.answer === true);
  if (confirmedSteps.length === 0) return y;

  // Identify top diseases across confirmed steps
  const peak = {};
  confirmedSteps.forEach((step) => {
    Object.entries(step.scores || {}).forEach(([d, v]) => {
      peak[d] = Math.max(peak[d] || 0, v);
    });
  });
  const diseases = Object.entries(peak)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([d]) => d);
  if (diseases.length === 0) return y;

  const n           = confirmedSteps.length;
  const legendRows  = Math.ceil(diseases.length / 2);
  const legendH     = legendRows * 5 + 4;
  const chartH      = 56;
  const xLabelH     = 22;
  const introH      = 13;
  const totalBlock  = introH + legendH + chartH + xLabelH + 14;

  y = ensureSpace(doc, y, totalBlock);
  y = sectionLabel(doc, "Confidence Evolution", y);

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...MUTED);
  doc.text(
    "Model probability for the leading conditions after each confirmed (Yes) symptom.",
    MARGIN,
    y
  );
  y += 7;

  // Legend — wraps onto multiple rows so it never overlaps the chart lines
  let lx = MARGIN;
  let ly = y;
  doc.setFontSize(7.5);
  diseases.forEach((d, idx) => {
    const color  = LINE_COLORS[idx % LINE_COLORS.length];
    const labelW = doc.getTextWidth(d) + 9;
    if (lx + labelW > PAGE_W - MARGIN) { lx = MARGIN; ly += 5; }
    doc.setFillColor(...color);
    doc.rect(lx, ly - 2.4, 3, 3, "F");
    doc.setTextColor(...INK);
    doc.text(d, lx + 4.5, ly);
    lx += labelW;
  });
  y = ly + 7;

  const chartW = CONTENT_W - 14;
  const chartX = MARGIN + 12;
  const chartY = y;

  // Gridlines and y-axis labels
  doc.setDrawColor(...BORDER);
  doc.setLineWidth(0.2);
  for (let p = 0; p <= 100; p += 20) {
    const gy = chartY + chartH - (p / 100) * chartH;
    doc.line(chartX, gy, chartX + chartW, gy);
    doc.setFontSize(6.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...MUTED);
    doc.text(`${p}%`, chartX - 3, gy + 1, { align: "right" });
  }

  // Chart border axes
  doc.setDrawColor(150);
  doc.setLineWidth(0.3);
  doc.line(chartX, chartY, chartX, chartY + chartH);
  doc.line(chartX, chartY + chartH, chartX + chartW, chartY + chartH);

  // Equal-slot x positioning — every node is centred in its own slot so
  // each x-axis label sits directly beneath its own data point with no
  // possibility of drifting toward a neighbouring point.
  const slotW = chartW / n;
  const xPos  = (i) => chartX + slotW * i + slotW / 2;

  // Plot one polyline per disease
  diseases.forEach((d, idx) => {
    const color = LINE_COLORS[idx % LINE_COLORS.length];
    doc.setDrawColor(...color);
    doc.setLineWidth(0.6);
    let prevX = null;
    let prevY = null;
    confirmedSteps.forEach((step, i) => {
      const v  = (step.scores && step.scores[d]) || 0;
      const x  = xPos(i);
      const yy = chartY + chartH - Math.min(v, 1) * chartH;
      if (prevX !== null) doc.line(prevX, prevY, x, yy);
      doc.setFillColor(...color);
      doc.circle(x, yy, 0.8, "F");
      prevX = x;
      prevY = yy;
    });
  });

  // Tick marks — short vertical lines from the baseline down to the label
  // area, one per confirmed step, aligned exactly under each node.
  doc.setDrawColor(...BORDER);
  doc.setLineWidth(0.25);
  confirmedSteps.forEach((_, i) => {
    const x = xPos(i);
    doc.line(x, chartY + chartH, x, chartY + chartH + 2.5);
  });

  // x-axis labels — rotated 45 degrees, anchored at the tick mark so the
  // start of each label is visually attached to its own node. Labels are
  // abbreviated when there are many confirmed symptoms so they never
  // overlap; every plotted point still has a visible label.
  const maxFullLabels = 10;
  doc.setFontSize(6.2);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...INK);
  confirmedSteps.forEach((step, i) => {
    const x = xPos(i);
    let label = (step.symptom || "").replace(/_/g, " ");
    if (n > maxFullLabels && label.length > 12) {
      label = label.slice(0, 11) + "...";
    }
    doc.text(label, x + 1, chartY + chartH + 6, { angle: 45, maxWidth: 26 });
  });

  doc.setTextColor(...INK);
  return chartY + chartH + xLabelH + 8;
}

// ─────────────────────────────────────────────
// MAIN ENTRY POINT
// ─────────────────────────────────────────────
export function generateTropiCareReport({ patient, diagnosis }) {
  if (!diagnosis) {
    throw new Error("No diagnosis data available to generate a report.");
  }

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  doc.setFont("helvetica", "normal");

  const reportId = makeReportId();
  const dateStr  = fmtDate(diagnosis.created_at);

  let y = drawHeader(doc, reportId, dateStr);
  y = drawPatientInfo(doc, patient, y);

  y = ensureSpace(doc, y, 40);
  y = drawClinicalSummary(doc, diagnosis, y);

  y = ensureSpace(doc, y, 30);
  y = drawDifferential(doc, diagnosis, y);

  y = ensureSpace(doc, y, 20);
  y = drawSymptoms(doc, diagnosis.active_symptoms, y);

  y = ensureSpace(doc, y, 30);
  y = drawRecommendations(doc, diagnosis.recommendation, y);

  y = drawConfidenceChart(doc, diagnosis.confidence_trajectory, y);

  // Signature line on the final page
  y = ensureSpace(doc, y, 26);
  doc.setDrawColor(...BORDER);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y + 14, MARGIN + 70, y + 14);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...MUTED);
  doc.text("Clinician signature / date", MARGIN, y + 18);

  drawPageFooter(doc);

  const stored   = getStoredUser();
  const safeName = field(
    patient?.name,
    patient?.patient_name,
    stored?.name
  ).replace(/[^a-z0-9]+/gi, "_");
  const fileDate = new Date().toISOString().slice(0, 10);
  doc.save(`TropiCare_Report_${safeName}_${fileDate}.pdf`);
}
