/*
 * TropiCare — Clinical PDF Report Generator
 */
import { jsPDF } from "jspdf";

const TEAL   = [12, 138, 126];
const TEAL_D = [10, 107, 98];
const INK    = [11, 23, 38];
const MUTED  = [91, 107, 124];
const RISK_RGB = {
  High:   [226, 61, 61],
  Medium: [232, 147, 15],
  Low:    [31, 157, 85],
  None:   [31, 157, 85],
};
const LINE_COLORS = [
  [12, 138, 126],
  [47, 111, 237],
  [232, 147, 15],
  [124, 92, 240],
  [226, 61, 61],
  [22, 121, 100],
];

const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN = 16;
const CONTENT_W = PAGE_W - MARGIN * 2;

function fmtDate(d) {
  const date = d ? new Date(d) : new Date();
  return date.toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" }) +
    " at " + date.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" });
}

function makeReportId() {
  const now = new Date();
  const stamp = now.toISOString().replace(/[-:T.]/g, "").slice(0, 14);
  return `TC-${stamp}`;
}

function ensureSpace(doc, cursorY, needed) {
  if (cursorY + needed > PAGE_H - 24) {
    doc.addPage();
    drawPageFooter(doc);
    return 22;
  }
  return cursorY;
}

function drawPageFooter(doc) {
  const page = doc.internal.getNumberOfPages();
  doc.setDrawColor(225);
  doc.setLineWidth(0.2);
  doc.line(MARGIN, PAGE_H - 16, PAGE_W - MARGIN, PAGE_H - 16);
  doc.setFontSize(7.5);
  doc.setTextColor(...MUTED);
  doc.text("TropiCare — AI-Guided Tropical Disease Symptom Checker", MARGIN, PAGE_H - 11);
  doc.text(`Page ${page}`, PAGE_W - MARGIN, PAGE_H - 11, { align: "right" });
  doc.text(
    "This report is generated by an automated screening tool and does not constitute a clinical diagnosis.",
    MARGIN, PAGE_H - 7
  );
}

function sectionLabel(doc, text, y) {
  doc.setFontSize(9.5);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...TEAL_D);
  doc.text(text.toUpperCase(), MARGIN, y);
  doc.setDrawColor(...TEAL);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, y + 1.5, PAGE_W - MARGIN, y + 1.5);
  doc.setFont("helvetica", "normal");
  return y + 7;
}

function drawHeader(doc, reportId, dateStr) {
  doc.setFillColor(...TEAL);
  doc.rect(0, 0, PAGE_W, 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("TropiCare", MARGIN, 13);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("Clinical Symptom Assessment Report", MARGIN, 20);

  doc.setFontSize(8);
  doc.text(`Report ID: ${reportId}`, PAGE_W - MARGIN, 12, { align: "right" });
  doc.text(`Generated: ${dateStr}`, PAGE_W - MARGIN, 18, { align: "right" });
  doc.setTextColor(...INK);
  return 38;
}

function drawPatientInfo(doc, patient, y) {
  y = sectionLabel(doc, "Patient Information", y);
  const rows = [
    ["Name", patient?.name || "Not provided"],
    ["Email", patient?.email || "Not provided"],
    ["Age", patient?.age ? `${patient.age} years` : "Not provided"],
    ["Gender", patient?.gender || "Not provided"],
  ];
  const colW = CONTENT_W / 2;
  rows.forEach((row, i) => {
    const col = i % 2;
    const rowIdx = Math.floor(i / 2);
    const x = MARGIN + col * colW;
    const ry = y + rowIdx * 7;
    doc.setFontSize(7.5);
    doc.setTextColor(...MUTED);
    doc.text(row[0].toUpperCase(), x, ry);
    doc.setFontSize(10);
    doc.setTextColor(...INK);
    doc.text(String(row[1]), x, ry + 4.5);
  });
  return y + Math.ceil(rows.length / 2) * 7 + 6;
}

function drawClinicalSummary(doc, diagnosis, y) {
  y = sectionLabel(doc, "Clinical Summary", y);
  const risk = diagnosis.risk || "Medium";
  const rgb  = RISK_RGB[risk] || RISK_RGB.Medium;
  const confPct = Math.round((diagnosis.confidence || 0) * 100);

  doc.setFillColor(248, 250, 250);
  doc.setDrawColor(225);
  doc.roundedRect(MARGIN, y, CONTENT_W, 32, 2, 2, "FD");

  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text("PREDICTED CONDITION", MARGIN + 6, y + 8);
  doc.setFontSize(15);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...INK);
  doc.text(diagnosis.disease || "No condition identified", MARGIN + 6, y + 17);
  doc.setFont("helvetica", "normal");

  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text(`Model confidence: ${confPct}%   ·   Method: ${diagnosis.method || "ensemble model"}`, MARGIN + 6, y + 24);

  // Risk badge
  const badgeW = 30;
  doc.setFillColor(...rgb);
  doc.roundedRect(PAGE_W - MARGIN - badgeW - 6, y + 6, badgeW, 9, 4.5, 4.5, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text(`${risk} Risk`, PAGE_W - MARGIN - badgeW - 6 + badgeW / 2, y + 12, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...INK);

  if (diagnosis.explanation) {
    doc.setFontSize(8.5);
    doc.setTextColor(...MUTED);
    const lines = doc.splitTextToSize(diagnosis.explanation, CONTENT_W - 12);
    doc.text(lines, MARGIN + 6, y + 29);
  }

  return y + 38;
}

function drawDifferential(doc, diagnosis, y) {
  const scores = diagnosis.all_scores || {};
  const others = Object.entries(scores)
    .filter(([d]) => d !== diagnosis.disease)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5);
  if (others.length === 0) return y;

  y = sectionLabel(doc, "Differential Diagnosis — Other Possibilities", y);
  doc.setFontSize(8.5);
  doc.setTextColor(...MUTED);
  doc.text("Condition", MARGIN, y);
  doc.text("Probability", PAGE_W - MARGIN, y, { align: "right" });
  y += 3;
  doc.setDrawColor(230);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 4;

  others.forEach(([d, v]) => {
    const pct = Math.round(v * 100);
    doc.setFontSize(9.5);
    doc.setTextColor(...INK);
    doc.text(d, MARGIN, y + 3);

    const barX = PAGE_W - MARGIN - 45;
    const barW = 30;
    doc.setFillColor(235, 238, 240);
    doc.roundedRect(barX, y, barW, 4, 1, 1, "F");
    doc.setFillColor(...MUTED);
    doc.roundedRect(barX, y, Math.max(barW * (pct / 100), 1), 4, 1, 1, "F");
    doc.setFontSize(9);
    doc.text(`${pct}%`, PAGE_W - MARGIN, y + 3.3, { align: "right" });
    y += 8;
  });
  return y + 3;
}

function drawSymptoms(doc, symptoms, y) {
  if (!symptoms || symptoms.length === 0) return y;
  y = sectionLabel(doc, `Reported Symptoms (${symptoms.length})`, y);
  const labels = symptoms.map((s) => s.replace(/_/g, " "));
  doc.setFontSize(9);
  doc.setTextColor(...INK);
  let x = MARGIN, lineY = y;
  labels.forEach((label) => {
    const w = doc.getTextWidth(label) + 6;
    if (x + w > PAGE_W - MARGIN) { x = MARGIN; lineY += 7; }
    doc.setFillColor(238, 252, 250);
    doc.setDrawColor(189, 240, 234);
    doc.roundedRect(x, lineY - 4.5, w, 6.5, 2, 2, "FD");
    doc.setTextColor(...TEAL_D);
    doc.setFontSize(8);
    doc.text(label, x + 3, lineY);
    doc.setTextColor(...INK);
    x += w + 3;
  });
  return lineY + 9;
}

function drawRecommendations(doc, rec, risk, y) {
  if (!rec) return y;
  y = sectionLabel(doc, "Clinical Recommendations", y);
  const items = [
    ["Home Care", rec.home_care],
    ["Recommended Test", rec.test],
    ["Doctor / Clinic Visit", rec.doctor],
    ["Safety Note", rec.safety],
  ].filter((i) => i[1]);

  items.forEach(([label, text]) => {
    const lines = doc.splitTextToSize(text, CONTENT_W - 8);
    const boxH = 8 + lines.length * 4.2;
    doc.setFillColor(250, 250, 251);
    doc.setDrawColor(232);
    doc.roundedRect(MARGIN, y, CONTENT_W, boxH, 1.5, 1.5, "FD");
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...TEAL_D);
    doc.text(label.toUpperCase(), MARGIN + 4, y + 5.5);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...INK);
    doc.text(lines, MARGIN + 4, y + 10.5);
    y += boxH + 4;
  });
  return y + 2;
}

function drawConfidenceChart(doc, trajectory, y) {
  if (!trajectory || trajectory.length === 0) return y;

  y = sectionLabel(doc, "Confidence Evolution — How the Assessment Changed", y);
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text("Model probability for the leading conditions as each symptom was answered.", MARGIN, y);
  y += 6;

  const chartH = 58;
  const chartW = CONTENT_W - 12;
  const chartX = MARGIN + 10;
  const chartY = y;

  // pick top diseases across the whole trajectory
  const peak = {};
  trajectory.forEach((step) => {
    Object.entries(step.scores || {}).forEach(([d, v]) => {
      peak[d] = Math.max(peak[d] || 0, v);
    });
  });
  const diseases = Object.entries(peak).sort((a, b) => b[1] - a[1]).slice(0, 5).map(([d]) => d);
  if (diseases.length === 0) return y;

  // axes + gridlines
  doc.setDrawColor(220);
  doc.setLineWidth(0.2);
  for (let p = 0; p <= 100; p += 20) {
    const gy = chartY + chartH - (p / 100) * chartH;
    doc.line(chartX, gy, chartX + chartW, gy);
    doc.setFontSize(6.5);
    doc.setTextColor(...MUTED);
    doc.text(`${p}%`, chartX - 2, gy + 1, { align: "right" });
  }
  doc.setDrawColor(150);
  doc.line(chartX, chartY, chartX, chartY + chartH);
  doc.line(chartX, chartY + chartH, chartX + chartW, chartY + chartH);

  const n = trajectory.length;
  const xStep = n > 1 ? chartW / (n - 1) : 0;

  // x-axis labels (rotated)
  doc.setFontSize(6);
  doc.setTextColor(...MUTED);
  trajectory.forEach((step, i) => {
    const x = chartX + i * xStep;
    const label = (step.symptom || "").replace(/_/g, " ");
    doc.text(label, x + 1, chartY + chartH + 9, { angle: 45 });
  });

  // lines
  diseases.forEach((d, idx) => {
    const color = LINE_COLORS[idx % LINE_COLORS.length];
    doc.setDrawColor(...color);
    doc.setLineWidth(0.5);
    let prevX = null, prevY = null;
    trajectory.forEach((step, i) => {
      const v = (step.scores && step.scores[d]) || 0;
      const x = chartX + i * xStep;
      const yy = chartY + chartH - Math.min(v, 1) * chartH;
      if (prevX !== null) doc.line(prevX, prevY, x, yy);
      doc.setFillColor(...color);
      doc.circle(x, yy, 0.6, "F");
      prevX = x; prevY = yy;
    });
  });

  // legend
  let lx = chartX, ly = chartY - 4;
  doc.setFontSize(7);
  diseases.forEach((d, idx) => {
    const color = LINE_COLORS[idx % LINE_COLORS.length];
    doc.setFillColor(...color);
    doc.rect(lx, ly - 2.2, 3, 3, "F");
    doc.setTextColor(...INK);
    doc.text(d, lx + 4.5, ly);
    lx += doc.getTextWidth(d) + 12;
    if (lx > chartX + chartW - 20) { lx = chartX; ly += 5; }
  });

  return chartY + chartH + 18;
}

export function generateTropiCareReport({ patient, diagnosis }) {
  if (!diagnosis) {
    throw new Error("No diagnosis data available to generate a report.");
  }

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const reportId = makeReportId();
  const dateStr = fmtDate(diagnosis.created_at);

  let y = drawHeader(doc, reportId, dateStr);
  y = drawPatientInfo(doc, patient, y);
  y = ensureSpace(doc, y, 40);
  y = drawClinicalSummary(doc, diagnosis, y);

  y = ensureSpace(doc, y, 30);
  y = drawDifferential(doc, diagnosis, y);

  y = ensureSpace(doc, y, 20);
  y = drawSymptoms(doc, diagnosis.active_symptoms, y);

  y = ensureSpace(doc, y, 30);
  y = drawRecommendations(doc, diagnosis.recommendation, diagnosis.risk, y);

  y = ensureSpace(doc, y, 80);
  y = drawConfidenceChart(doc, diagnosis.confidence_trajectory, y);

  // Signature line on the final page
  y = ensureSpace(doc, y, 24);
  doc.setDrawColor(200);
  doc.line(MARGIN, y + 14, MARGIN + 70, y + 14);
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text("Clinician signature / date", MARGIN, y + 18);

  drawPageFooter(doc);

  const safeName = (patient?.name || "patient").replace(/[^a-z0-9]+/gi, "_");
  const fileDate = new Date().toISOString().slice(0, 10);
  doc.save(`TropiCare_Report_${safeName}_${fileDate}.pdf`);
}
